/Users/ramazanhanaev/Desktop/instagram_telegram_bot_beckap/instagram_telegram_bot_reserv/fresh_env/lib/python3.12/site-packages/telegram/utils/request.py:49: UserWarning: python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.
  warnings.warn(
/Users/ramazanhanaev/Desktop/instagram_telegram_bot_beckap/instagram_telegram_bot_reserv/fresh_env/lib/python3.12/site-packages/apscheduler/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
2025-08-01 14:37:52,250 - __main__ - INFO - Инициализация базы данных...
2025-08-01 14:37:52,253 - database.db_manager - INFO - База данных инициализирована
2025-08-01 14:37:52,253 - __main__ - INFO - Запуск планировщика задач...
2025-08-01 14:37:52,253 - utils.scheduler - INFO - Планировщик задач запущен
2025-08-01 14:37:52,253 - __main__ - INFO - Запуск обработчика очереди задач...
2025-08-01 14:37:52,254 - utils.task_queue - INFO - 🚀 Запущен адаптивный обработчик очереди задач
2025-08-01 14:37:52,254 - utils.task_queue - INFO - Запущен поток обработки очереди задач
2025-08-01 14:37:52,254 - __main__ - INFO - Запуск мониторинга системных ресурсов...
2025-08-01 14:37:52,254 - utils.system_monitor - INFO - 🖥️ Запущен мониторинг системных ресурсов (профиль: macbook)
2025-08-01 14:37:52,254 - __main__ - INFO - Запуск умного валидатора аккаунтов...
2025-08-01 14:37:52,277 - utils.smart_validator_service - INFO - 🚀 Инициализирован умный валидатор (проверки: 2, восстановления: 1)
2025-08-01 14:37:52,277 - utils.smart_validator_service - INFO - ✅ Умный валидатор запущен
2025-08-01 14:37:52,278 - __main__ - INFO - Запуск Telegram бота...
2025-08-01 14:37:52,279 - py.warnings - WARNING - /Users/ramazanhanaev/Desktop/instagram_telegram_bot_beckap/instagram_telegram_bot_reserv/fresh_env/lib/python3.12/site-packages/telegram/ext/conversationhandler.py:287: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
  warnings.warn(

2025-08-01 14:37:52,285 - telegram_bot.bot - INFO - Бот настроен и готов к работе
2025-08-01 14:37:52,285 - apscheduler.scheduler - INFO - Scheduler started
2025-08-01 14:37:52,644 - __main__ - INFO - Бот запущен и готов к работе!
2025-08-01 14:37:54,268 - utils.task_queue - INFO - 🔧 Адаптация нагрузки: потоков 50 → 4 | Уровень: Стандартная активность бота
2025-08-01 14:37:56,814 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:37:56,814 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:37:56,815 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:02,043 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:02,044 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:02,044 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:07,185 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:07,185 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:07,185 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:12,324 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:12,324 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:12,325 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:18,471 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:18,472 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:18,473 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
